### PR TITLE
fix: Video issues in the demo delete, play, current image

### LINKED ISSUE #1089: [Bug] Basic video tool demo
### Describe the Bug

https://www.cornerstonejs.org/live-examples/videotools

and 

https://www.cornerstonejs.org/live-examples/videorange

### Steps to Reproduce

Delete annotation does nothing

### The current behavior

1. Key image needs a click
2. The video starts playing like couple of seconds and then it pauses
3. What is `Current Image` 

### The expected behavior

Also we should be able to programmatically add the keyimage, right now it seems like we have to click on the image, a utility would be nice to have (pretty sure is a must)

If the video should start from pause it should play

I still don't understand the use of `current image` really. Can you explain that in the instructions? what is the difference between current image and start range and end range

### OS

d

### Node version

d

### Browser

d

### PR DESCRIPTION
**Pull request by wayfarer3130**
### Context

The video demo pages had a bit of functionality broken - fixes #1089
* Delete annotation via a button
* Video started playing automatically, and navigated 1/4 second in
* 'Current Image' button was unclear, renamed to Remove Range as agreed

Also fixes [#1092]

### Changes & Results

See context

### Testing

yarn example videoTools
yarn example videoRange

#### PR

- [] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [] My code has been well-documented (function documentation, inline comments,
  etc.)

- [] I have run the `yarn build:update-api` to update the API documentation, and have
  committed the changes to this PR. (Read more here https://www.cornerstonejs.org/docs/contribute/update-api)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [] "OS: 
- [] "Node version: 
- [] "Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

File: packages/core/src/RenderingEngine/VideoViewport.ts [hunk 1]
```diff
@@ -235,16 +243,19 @@ class VideoViewport extends Viewport implements IVideoViewport {
...
       // 1 based range setting
       this.setFrameRange([1, numberOfFrames]);
-      this.play();
       // This is ugly, but without it, the video often fails to render initially
       // so having a play, followed by a pause fixes things.
-      // 100 ms is a tested value that seems to work to prevent exceptions
+      // 25 ms is a tested value that seems to work to prevent exceptions
       return new Promise((resolve) => {
-        window.setTimeout(() => {
+        this.initialRender = () => {
```
Comment (sedghi) [inline packages/core/src/RenderingEngine/VideoViewport.ts:250]: why this initialRender is inside the promise since it is only a function

File: packages/tools/examples/videoRange/index.ts [hunk 2]
```diff
@@ -83,10 +84,50 @@ const baseEventDetail = {
...
+  title: 'Play',
+  onClick: togglePlay,
+  defaultToggle: false,
+});
+
+addButtonToToolbar({
+  id: 'CreateKey',
+  title: 'Create Key Image',
+  onClick: () => {
+    const annotation = {
```
Comment (sedghi) [inline packages/tools/examples/videoRange/index.ts:98]: can we create a utility for this please

File: packages/tools/src/tools/base/AnnotationTool.ts [hunk 3]
```diff
@@ -21,9 +22,12 @@ import {
   PublicToolProps,
   IToolBinding,
 } from '../../types';
+import { addAnnotation } from '../../stateManagement/annotation/annotationState';
 import { StyleSpecifier } from '../../types/AnnotationStyle';
+import { triggerAnnotationModified } from '../../stateManagement/annotation/helpers/state';
+import { add } from '@kitware/vtk.js/Common/Core/Math';
```
Comment (sedghi) [inline packages/tools/src/tools/base/AnnotationTool.ts:28]: I think this import is a mistake

**Review by sedghi — COMMENTED** [review]
Looks awesome thanks

**Review by sedghi — APPROVED** [review]
Looks awesome thanks
