### PR TITLE
fix(freehandContourSeg): freehand contour segmentation example (#1084)

### LINKED ISSUE #1084: [Bug] Freehand cnotour segmentation tool
### Describe the Bug

The demo shows three unrelated buttons

### Steps to Reproduce

https://www.cornerstonejs.org/live-examples/planarfreehandcontoursegmentationtool

CleanShot 2024-02-14 at 15 20 01

### The expected behavior

we should remove the 
1. render selected 
3. toggle calculate stats	

Toggle interpolation should be renamed to toggle smoothing -> and debugged why it does not work

### OS

d

### Node version

d

### Browser

d

### PR DESCRIPTION
**Pull request by lscoder**
fixes #1084 

Fix Freehand Contour Segmentation Tool example
- removed "render selected" and  "toggle calculate stats" buttons
- changed "toggle interpolation" to "toggle smoothing" and made some changes to get it working.

### CODE REVIEW

File: packages/tools/examples/planarFreehandContourSegmentationTool/index.ts [hunk 1]
```diff
@@ -340,6 +264,40 @@ addButtonToToolbar({
   },
 });
 
+let smoothingEnabled = false;
+const toggleSmoothingButtonContainer = document.createElement('span');
+
+// Reserve some space in the toolbar because this input is added later
+toolbar.appendChild(toggleSmoothingButtonContainer);
+
+function addToggleSmoothingButton(toolGroup) {
```
Comment (sedghi) [inline packages/tools/examples/planarFreehandContourSegmentationTool/index.ts:273]: We have a toggle in utils, use that, it is the same as show/hide all segments element

**Review by sedghi — CHANGES_REQUESTED** [review]
can you fix this one as well? 

https://deploy-preview-1100--cornerstone-3d-docs.netlify.app/live-examples/planarfreehandroitool

**Comment by lscoder** [comment]
> can you fix this one as well?
> 
> https://deploy-preview-1100--cornerstone-3d-docs.netlify.app/live-examples/planarfreehandroitool

Fixed!

**Review by sedghi — APPROVED** [review]
