### PR TITLE
fix: take into account storePointData setting

### LINKED ISSUE #1709: [Bug] RectangleROI & EllipseROI ignoring storePointData configuration
### Describe the Bug

`pointsInShape `are being stored (or provided in `CORNERSTONE_TOOLS_ANNOTATION_COMPLETED` event, (`event.detail.anntotation` ) with storePointData set to false

### Steps to Reproduce

1. After initializing cs, tools and a **toolGroup**: 
```
toolGroup.setToolActive('RectangleROI' { bindings: [{ mouseButton: 1 }] });
toolGroup.setToolConfiguration('RectangleROI', { storePointData: false }); // optional, it's set to false by default
console.log(toolGroup.getToolConfiguration('RectangleROI'));
``` 
2. Draw the annotation on a StackViewport and log it (or store it anywhere you can see it)
```
Cornerstone3D.eventTarget.addEventListener("CORNERSTONE_TOOLS_ANNOTATION_COMPLETED", (e) => {
    console.log(e.detail.annotation);
}
```
3. You will be able to see "`pointsInShape`" atribute in data.cachedStats.imageId...{}

### The current behavior

`pointsInShape `are being stored (or provided in `CORNERSTONE_TOOLS_ANNOTATION_COMPLETED` event, (`event.detail.anntotation` ) with storePointData set to false

### The expected behavior

Getting the annotation object without points data when storePointData is set to false

### OS

Windows 11

### Node version

22.11.0

### Browser

Chrome, Firefox

### PR DESCRIPTION
**Pull request by daker**
### Context
fix #1709

#### PR

- [x] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [x] My code has been well-documented (function documentation, inline comments,
  etc.)

- [] I have run the `yarn build:update-api` to update the API documentation, and have
  committed the changes to this PR. (Read more here https://www.cornerstonejs.org/docs/contribute/update-api)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [] "OS: 
- [] "Node version: 
- [] "Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

File: packages/tools/src/tools/annotation/EllipticalROITool.ts [hunk 1]
```diff
@@ -1134,16 +1134,18 @@ class EllipticalROITool extends AnnotationTool {
...
+            this.configuration.statsCalculator.statsCallback,
+            {
+              boundsIJK,
+              imageData,
+              isInObject: (pointLPS) =>
+                pointInEllipse(ellipseObj, pointLPS, { fast: true }),
+              returnPoints: this.configuration.storePointData,
+            }
+          )
+        : null;
```
Comment (sedghi) [inline packages/tools/src/tools/annotation/EllipticalROITool.ts:1148]: I don't think this is correct. We should still perform the `statsCallback` even if `storePointData` is not `true` (calculating mean, max, std, etc.). The only purpose of `storePointData` here is to decide whether to store the points inside the elliptical or rectangular ROI in the annotation object.

Comment (daker) [reply packages/tools/src/tools/annotation/EllipticalROITool.ts:1148]: i will update the code

**Review by sedghi — APPROVED** [review]
Thanks a lot
