### PR TITLE
fix(events): ANNOTATION_REMOVED event listener on removing ALL annotations.

### LINKED ISSUE #1056: cornerstone.annotation.state.removeAllAnnotations() should dispatchEvent for ANNOATION_REMOVED
### What feature or change would you like to see made?

cornerstone.annotation.state.removeAllAnnotations() should dispatchEvent for ANNOATION_REMOVED

### Why should we prioritize this feature?

It's the expected behavior of the code. It makes sense for ANNOTATION_REMOVED to fire when an annotation is removed.

### PR DESCRIPTION
**Pull request by ChandlerClevenger**
### Context
Fixes #1056 

### Changes & Results
Moved code from FrameOfReferenceSpecificAnnotationManager into annotationState and re-used the same annotation removal code.

### Testing
I used the annotationVisibility example and added another button to remove selected annotation OR if none are selected it would remove them all. I tested this way and it worked.

#### PR

- [x] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [x] My code has been well-documented (function documentation, inline comments,
  etc.)

- [x] I have run the `yarn build:update-api` to update the API documentation, and have
  committed the changes to this PR. (Read more here https://www.cornerstonejs.org/docs/contribute/update-api)
N/A really

#### Public Documentation Updates

- [x] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [x] "OS: Windows 11
- [x] "Node version: Node v20.12.2
- [x] "Browser: Chrome Version 124.0.6367.119 (Official Build) (64-bit)
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

File: packages/tools/src/stateManagement/annotation/FrameOfReferenceSpecificAnnotationManager.ts [hunk 1]
```diff
@@ -270,6 +275,13 @@ class FrameOfReferenceSpecificAnnotationManager implements IAnnotationManager {
         delete annotations[groupKey];
       }
     }
+
+    if (annotationToRemove !== null) {
+      triggerEvent(eventTarget, csToolEvents.ANNOTATION_REMOVED, {
+        annotation: annotationToRemove,
+        annotationManagerUID: this.uid,
+      });
+    }
```
Comment (sedghi) [inline packages/tools/src/stateManagement/annotation/FrameOfReferenceSpecificAnnotationManager.ts:284]: If you examine other sections in this file, we don't publish events here but rather in the `annotationState`. Could you perhaps follow the same pattern?

File: packages/tools/src/stateManagement/annotation/annotationState.ts [hunk 2]
```diff
@@ -223,16 +217,6 @@ function removeAnnotation(annotationUID: string): void {
   );
 
   manager.removeAnnotation(annotationUID);
-
-  // trigger annotation removed
-  const eventType = Events.ANNOTATION_REMOVED;
```
Comment (sedghi) [inline packages/tools/src/stateManagement/annotation/annotationState.ts:228]: I think make a copy here

**Review by sedghi — COMMENTED** [review]
see my comments please

File: packages/tools/src/stateManagement/annotation/annotationState.ts [hunk 3]
```diff
@@ -251,7 +239,32 @@ function getAnnotation(annotationUID: string): Annotation {
...
+ * Removes all annotations associated with the specified group (FrameOfReferenceUID) and tool, or
+ * all annotations for the group (FrameOfReferenceUID) if the tool name is not provided.
+ * @param groupKey - The group key to remove annotations for (in default manager it is FrameOfReferenceUID).
+ * @param toolName - Optional. The name of the tool to remove annotations for.
+ */
+function removeAnnotations(groupKey: string, toolName?: string): void {
+  const manager = getAnnotationManager();
+  const removedAnnotations = manager.removeAnnotations(groupKey, toolName);
+
+  for (const annotation of removedAnnotations) {
```
[the remark this answers is not in the document]
Comment (ChandlerClevenger) [reply packages/tools/src/stateManagement/annotation/annotationState.ts]: I believe it is meant to be AnnotationGroupSelector instead of string? I will make this change as that is how other functions in this file handle this.

**Comment by ChandlerClevenger** [comment]
I made that function parameter more in-line with the other functions in that file. Thank you for these reviews.

**Review by sedghi — APPROVED** [review]
Thanks, I just re-orderd the params to be consistent with other annotation state APIs
