### PR TITLE
fix: trigger LabelChange for LabelTool

### LINKED ISSUE #1858: [Bug] Cannot destructure property 'annotation' of 'this.editData' as it is undefined
### Describe the Bug

If you put Label on canvas, then call the cancelActiveManipulations function while the "Label" tool is active, this error will occur.

### Steps to Reproduce

1. Place Label on Canvas
2. Call cancelActiveManipulations

### The current behavior

LabelTool.js:182 Uncaught TypeError: Cannot destructure property 'annotation' of 'this.editData' as it is undefined.
    at LabelTool.cancel (LabelTool.js:182:25)
    at Module.cancelActiveManipulations (cancelActiveManipulations.js:11:1)

### The expected behavior

No errors

### OS

Windows 10 x64

### Node version

20.18.3

### Browser

Google Chrome

### LINKED ISSUE #1863: [Bug] LabelTool does not generate Modified event after moving
### Describe the Bug

LabelTool does not generate Modified event after moving

### Steps to Reproduce

1. Place label
2. Try to move label

### The current behavior

No Modified event after moving

### The expected behavior

Fires Modified event after moving

### OS

Windows 10 x64

### Node version

20.18.3

### Browser

Chrome

### PR DESCRIPTION
**Pull request by daker**
### Context
fixes the icon name of LabelTool
fixes #1863
fixes #1858

#### PR

- [x] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [x] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [x] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [x] "OS: 
- [x] "Node version: 
- [x] "Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

File: packages/tools/src/cursors/SVGCursorDescriptor.ts [hunk 1]
```diff
@@ -229,8 +229,8 @@ const CursorSVG: Record<string, SVGCursorDescriptor> = {
       y: 1792,
     },
   }),
-  TextMarker: extend(BASE, {
-    name: 'TextMarker',
+  Label: extend(BASE, {
```
Comment (sedghi) [inline packages/tools/src/cursors/SVGCursorDescriptor.ts:232]: why is this changed?

Comment (daker) [reply packages/tools/src/cursors/SVGCursorDescriptor.ts:232]: To have the correct icon for LabelTool

Comment (sedghi) [reply packages/tools/src/cursors/SVGCursorDescriptor.ts:232]: Oh i see it is icons
