### PR TITLE
fix(brush cursor): only show innter circle on dynamic threshold

### LINKED ISSUE #1086: [Bug] Dynamic threshold brush tool inner circle size
### Describe the Bug

Seems like we now have the inner circle shown for all the brush tools even if they are not threshold brush. 

### Steps to Reproduce

https://www.cornerstonejs.org/live-examples/labelmapsegmentationdynamicthreshold

### The current behavior

s

### The expected behavior

1. We should only show the inner circle for the dynamic threshold brush tool
2. It should be dynamically size with respect to its radius, right now it is fixed size

### OS

d

### Node version

d

### Browser

d

### PR DESCRIPTION
**Pull request by sedghi**
fixes #1086 

#### PR

- [] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [] My code has been well-documented (function documentation, inline comments,
  etc.)

- [] I have run the `yarn build:update-api` to update the API documentation, and have
  committed the changes to this PR. (Read more here https://www.cornerstonejs.org/docs/contribute/update-api)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [] "OS: 
- [] "Node version: 
- [] "Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

File: packages/tools/src/tools/segmentation/BrushTool.ts [hunk 1]
```diff
@@ -584,6 +584,33 @@ class BrushTool extends BaseTool {
       rightCursorInWorld,
     ];
 
+    const activeStrategy = this.configuration.activeStrategy;
+
+    // Note: i don't think this is the best way to implement this
+    // but don't think we have a better way to do it for now
+    if (activeStrategy.startsWith('THRESHOLD')) {
```
Comment (wayfarer3130) [inline packages/tools/src/tools/segmentation/BrushTool.ts:591]: Instead of this, create a new active strategy callback that returns configuration values, can call that method and get the data from the response.  That way you can change the inner circle size based on whatever the strategy decides.

Comment (sedghi) [reply packages/tools/src/tools/segmentation/BrushTool.ts]: Done

**Review by wayfarer3130 — APPROVED** [review]
